// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GeometryLines : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GeometryLines GetRootAsGeometryLines(ByteBuffer _bb) { return GetRootAsGeometryLines(_bb, new GeometryLines()); }
  public static GeometryLines GetRootAsGeometryLines(ByteBuffer _bb, GeometryLines obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GeometryLines __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FloatVector? Points(int j) { int o = __p.__offset(4); return o != 0 ? (FloatVector?)(new FloatVector()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int PointsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GeometryLines> CreateGeometryLines(FlatBufferBuilder builder,
      VectorOffset pointsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    GeometryLines.AddPoints(builder, pointsOffset);
    return GeometryLines.EndGeometryLines(builder);
  }

  public static void StartGeometryLines(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPoints(FlatBufferBuilder builder, VectorOffset pointsOffset) { builder.AddOffset(0, pointsOffset.Value, 0); }
  public static void StartPointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<GeometryLines> EndGeometryLines(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // points
    return new Offset<GeometryLines>(o);
  }
}


static public class GeometryLinesVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Points*/, 12 /*FloatVector*/, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
