// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum GeometryClass : sbyte
{
  NONE = 0,
  LINES = 1,
  ELLIPSE_ARC = 2,
  CLOTHOID = 3,
  PARABOLA = 4,
};

